name: Build and Deploy
on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deepin website update
        run: curl ${{ secrets.DEEPIN_WEBSITE_WEBHOOK }}
